### ISSUE TITLE
i3wm running fairly slow, with compton consuming up to 97% of CPU and firefox 90%

### ISSUE THREAD

**Issue by patrickwoolf** [adi1090x/archlinux#3]

**Comment by adi1090x** [comment]
it depends on what you running on firefox.

**Comment by patrickwoolf** [comment]
I find out that killing compton boost the system fairly good (blur not working so I I tried killing compton)

**Comment by Thomashighbaugh** [comment]
## Hardware
Well if your system's running a lower end or lower cpu, this might explain the issue, which I presume you are aware of already. 
### BIOS Settings
Sometimes something happens resetting your system's CMOS battery and the BIOS settings revert to default. This can, depending on the sadism of the MoBo company, reset settings that make the system extremely incapable when it is otherwise not if configured correctly. To check this out, boot to BIOS and run through all your settings, make sure the Hyperthreading is on, make sure the GPU is on (if such a setting is there) and check out the system info and make sure everything is appearing as it should. Your system is a unique BIOS butterfly I wish I could help more with that, but such is the nature of the MoBo.

## GPU: Check Your System's Drivers 
Additionally, what's your system's on-chip GPU or does it have a separate GPU? If its eating your CPU resources running graphical programs, it may be the result of not having a GPU driver properly installed or some other issue with the system's rendering of the graphics using its GPU functionality that is causing the CPU to pick up that on top of its typical activities.  

## Alternative Applications
What about replacing compton with picom? Since the cool kids use picom now, this may help out if its something with compton having some bug or not working with your CPU. 

Check it out [HERE](https://github.com/yshui/picom)
Arch Wiki Entry [HERE](https://wiki.archlinux.org/index.php/Picom)

**Comment by adi1090x** [comment]
Hope everything is clear.
